config/routes.rb
Rails.application.routes.draw do
  root 'land#landingpage'
  resources :articles
  resources :users
  get 'signup', to: 'users#new'
  # get 'login', to: 'sessions#new'
  # post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :sessions, only: %w[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }

end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: {minimum: 3, maximum: 25}
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  validates :username, presence: true,uniqueness: {case_sensitive:false}, length: {minimum: 3, maximum:25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:true, uniqueness: {case_sensitive:false}, length: {maximum: 105},format: {with: VALID_EMAIL_REGEX}
  has_secure_password



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = 'You must be logged in to perform that action'
      redirect_to new_session_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was successfully created."
      redirect_to @article
    else
      render 'new', status: :unprocessable_entity
    end
  end
  def update
    if
      @article.update(article_params)
      flash[:notice] = "Article was updated successfully"
      redirect_to @article
    else
      render 'edit', status: :unprocessable_entity
    end
  end
  def destroy
    @article.destroy
    redirect_to articles_path, status: :see_other
  end



  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if current_user != @article.user
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def new

  end
  def index

  end
  def show

  end
end

app/controllers/land_controller.rb
class LandController < ApplicationController
  def landingpage
    redirect_to articles_path if logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfull"
      redirect_to articles_path
    else
      flash.now[:alert] = "Wrong credentails"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show,:edit,:update]
  before_action :require_user, only: [:edit,:update]
  before_action :require_same_user, only: [:edit, :update]
  def show
    @article = @user.articles.paginate(page: params[:page], per_page: 5)
    @user = User.find(params[:id])
    @articles = @user.articles
  end
  def index
    @users = User.paginate(page: params[:page], per_page:5)
  end
  def new
    @user = User.new
  end
  def edit
  end
  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated"
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "welcome to the blog #{@user.username}, successfully signed up"
      redirect_to articles_path
    else
      render 'new', status: :unprocessable_entity
    end
  end
  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    flash[:alert] = "You can edit your own account"
    redirect_to @user
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user,options = {size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt:user.username)
  end


end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/land_helper.rb
module LandHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcom_helper.rb
module WelcomHelper
end

app/views/articles/_article.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Articles</title>
  <!-- Add Bootstrap CSS CDN link -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
<%= link_to 'All Users', users_path, class: "nav-link" %>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Creator</th>
    <th>Action</th>
  </tr>
  </thead>
  <tbody>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.description %></td>
      <td><% if article.user %>
          by <%= link_to article.user.username, user_path(article.user) %>
          <% end %>
      </td>
      <td>
        <%= link_to "Show", article_path(article), class: "btn btn-primary mr-2" %>
        <%= link_to "Edit", edit_article_path(article), class: "btn btn-secondary mr-2" %>
        <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'Create Article', new_article_path, class: "btn btn-success" %>

<!-- Add Bootstrap JS and jQuery CDN links -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

app/views/articles/_form.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>New Article</title>
  <!-- Add Bootstrap CSS CDN link -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <%= render 'shared/errors', obj: @article %>

          <%= form_with(model: @article, local: true, class: 'needs-validation', novalidate: true) do |f| %>
            <div class="form-group">
              <%= f.label :title %>
              <%= f.text_field :title, class: 'form-control', required: true %>
              <div class="invalid-feedback">Please enter a title.</div>
            </div>

            <div class="form-group">
              <%= f.label :description %>
              <%= f.text_area :description, class: 'form-control', required: true %>
              <div class="invalid-feedback">Please enter a description.</div>
            </div>

            <%= f.submit 'Submit', class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Add Bootstrap JS and jQuery CDN links -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

<%= link_to 'Cancel', articles_path %>

app/views/articles/index.html.erb
<h1>Showing Article Listing Page</h1>
<% if logged_in? %>
  <%= link_to 'Logout', logout_path, method: :delete %>
  <p>Welcome to the Blog <%= current_user.username %></p>
<% else %>
  <%= link_to "Login", new_session_path, class: "nav-link" %>
<% end %>
<%= render 'article' %>
<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<%= render 'form' %>
<%= link_to 'Return to articles', articles_path %>

app/views/articles/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Showing Article Detail</title>
  <!-- Add Bootstrap CSS CDN link -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
<div class="container mt-5">
  <div class="card">
    <div class="card-body">
      <h1 class="card-title mb-4">Showing Article Detail</h1>
      <p class="card-text"><strong>Title: </strong><%= @article.title %></p>
      <p class="card-text"><strong>Description: </strong><%= @article.description %></p>
      <p class="card-text">by ~ <%= @article.user.username if @article.user %></p>
      <div class="btn-group">
        <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-primary mr-2' %>
        <%= link_to "Delete", article_path(@article), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-danger mr-2' %>
        <%= link_to 'Home', articles_path, class: 'btn btn-secondary' %>
      </div>
    </div>
  </div>
</div>

<!-- Add Bootstrap JS and jQuery CDN links -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

app/views/land/landingpage.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Blog App</title>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <!-- Custom CSS -->
  <style>
      body {
          padding-top: 60px;
          display: flex;
          flex-direction: column;
          min-height: 100vh;
          font-family: Arial, sans-serif;
      }

      .navbar {
          background-color: #343a40;
      }

      .jumbotron {
          background-color: #f8f9fa;
          padding: 3rem;
      }

      .jumbotron h1 {
          font-size: 3rem;
          margin-bottom: 1.5rem;
      }

      .jumbotron p {
          font-size: 1.5rem;
          margin-bottom: 2rem;
      }

      .jumbotron .btn {
          font-size: 1.5rem;
          padding: 0.75rem 2rem;
      }

      .feature-box {
          margin-bottom: 3rem;
      }

      .feature-box h2 {
          font-size: 2rem;
          margin-bottom: 1rem;
      }

      .feature-box p {
          font-size: 1.25rem;
      }

      .footer {
          background-color: #343a40;
          padding: 1.5rem 0;
          color: #fff;
          margin-top: auto;
      }

      .footer span {
          font-size: 1rem;
      }
  </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="#">Blog App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to "Login", new_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "SignUp", signup_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="jumbotron">
  <div class="container">
    <h1 class="display-4">Welcome to the Blog App!</h1>
    <p class="lead">Start sharing your thoughts and ideas with the world.</p>
    <a class="btn btn-primary btn-lg" href="#" role="button">Get Started</a>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="feature-box">
        <h2>Discover</h2>
        <p>Explore a wide range of blog posts on various topics.</p>
      </div>
    </div>
    <div class="col-md-4">
      <div class="feature-box">
        <h2>Engage</h2>
        <p>Connect with fellow bloggers, leave comments, and start discussions.</p>
      </div>
    </div>
    <div class="col-md-4">
      <div class="feature-box">
        <h2>Create</h2>
        <p>Write and publish your own blog posts to share your unique perspective.</p>
      </div>
    </div>
  </div>
</div>

<footer class="footer bg-dark text-white">
  <div class="container text-center">
    <span>&copy; 2023 Blog App. All rights reserved.</span>
  </div>
</footer>

<!-- Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</body>
</html>

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg| %>
  <%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Section4</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    </div>
<%end%>

app/views/users/_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Signup Page</title>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <!-- Custom CSS -->
  <style>
      body {
          padding-top: 60px;
          font-family: Arial, sans-serif;
          background-color: #f8f9fa;
      }
      .card {
          max-width: 400px;
          margin: 0 auto;
          box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      }
      .card-header {
          background-color: #007bff;
          color: #fff;
          text-align: center;
          font-weight: bold;
          padding: 20px;
      }
      .card-body {
          padding: 30px;
      }
      .form-group label {
          font-weight: bold;
          color: #007bff;
      }
      .btn-primary {
          background-color: #007bff;
          border-color: #007bff;
      }
      .btn-primary:hover {
          background-color: #0069d9;
          border-color: #0062cc;
      }
      .text-info {
          color: #17a2b8;
      }
      h3 {
          margin-top: 0;
      }
  </style>
</head>
<body>
<div class="card">
  <div class="card-header text-white">
    <h3>Sign Up</h3>
  </div>
  <div class="card-body">
    <%= render 'shared/errors', obj: @user %>
    <%= form_with(model: @user, local: true) do |f| %>
      <div class="form-group">
        <%= f.label :username %>
        <%= f.text_field :username, class: "form-control rounded", placeholder: "Enter a username" %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control rounded", placeholder: "Enter your email address" %>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control rounded", placeholder: "Choose a password" %>
      </div>

      <div class="form-group text-center">
        <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account", class: "btn btn-primary btn-lg") %>
      </div>
    <% end %>


  </div>
</div>

<!-- Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</body>
</html>

app/views/users/edit.html.erb
<%= link_to gravatar_for(@user), user_path(@user) %>
<%= render 'form' %>
<%= link_to 'Return to articles', articles_path %>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>All Users</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container">
  <h1>All users</h1>

  <table class="table table-striped table-hover">
    <thead class="thead-dark">
    <tr>
      <th scope="col">Username</th>
      <th scope="col">Articles</th>
      <th scope="col">Actions</th>
      <th scope="col">Joined</th>
    </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user, class: "text-decoration-none" %></td>
        <td><%= pluralize(user.articles.count, "article") %></td>
        <td>
          <%= link_to "View Profile", user, class: "btn btn-primary btn-sm me-2" %>
          <%= link_to "Edit Profile", edit_user_path(user), class: "btn btn-secondary btn-sm" %>
        </td>
        <td>Joined <%= time_ago_in_words(user.created_at) %> ago</td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <div class="flickr_pagination">
    <%= will_paginate @user, :container => false %>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size:200 %>
<%= link_to "Edit Profile", edit_user_path(@user) %>
<%= render 'articles/article' %>
<%= link_to 'Return to articles', articles_path %>